### ISSUE TITLE
Why is Dotenv loaded on init? This breaks if you use AWS SecretManager or any other Ruby on Rails ENV loading tool

### ISSUE THREAD

**Issue by dmix** [mailerlite/mailerlite-ruby#27] opened 2024-11-12 18:36 UTC
Note here, it checks for require in the root of the file, without even calling `Mailerlite::Client`

https://github.com/mailerlite/mailerlite-ruby/blob/12186cc0cd7a0dc18ef06a7146eb20129603d2b0/lib/mailerlite/client.rb#L8

Ruby on Rails via bundler will auto-require imports. So this essentially forces users of `mailerlite-ruby` to use Dotenv in their Rails projects, as it loads before any other ENV loading gem. DOTENVs own documentation recommends against using it in Production. But it seems to be a hard dependency here.

So despite having MAILERLITE_API_TOKEN in my `application.yml` and accessible in `ENV` once my environment is loaded and also validated by `AWS::SecretManager` I get this error:

```
Dotenv::MissingKeys: Missing required configuration key: ["MAILERLITE_API_TOKEN"]
/Users/dmix/.rvm/gems/ruby-2.7.8/gems/dotenv-2.8.1/lib/dotenv.rb:79:in `require_keys'
/Users/dmix/.rvm/gems/ruby-2.7.8/gems/mailerlite-ruby-1.0.5/lib/mailerlite/client.rb:8:in `<top (required)>'
/Users/dmix/.rvm/gems/ruby-2.7.8/gems/mailerlite-ruby-1.0.5/lib/mailerlite.rb:3:in `require_relative'
/Users/dmix/.rvm/gems/ruby-2.7.8/gems/mailerlite-ruby-1.0.5/lib/mailerlite.rb:3:in `<top (required)>'
/Users/dmix/.rvm/gems/ruby-2.7.8/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/dmix/.rvm/gems/ruby-2.7.8/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/dmix/.rvm/gems/ruby-2.7.8/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
```

the only way around this in Ruby on Rails is to set `require: false` inside my Gemfile and `require 'mailerlite'` explicitly inside a rake task after enviornment:

```
namespace :mailerlite do
  desc "Upload new subscribers to MailerLite"
  task sync: :environment do
    require "mailerlite-ruby"
```

this is very atypical in ruby on rails. And makes using it awkward to use elsewhere depending on how the stack loads.

**Comment by humandoing** [comment] 2024-11-13 16:26
I strongly agree with @dmix and forked the repo to remove the requirement. Definitely not my first choice or preference. 

Would be great to allow the secret (api key) to be set in an initializer (if using Rails), or have an order of operations to check for it via Dotenv as one potential option instead of forcing people to use it.

**Comment by humandoing** [comment] 2024-11-13 16:27
Also this is somewhat a duplicate of #25

**Comment by dinomh** [comment] 2024-12-11 13:48
Thanks for your feedback! In the latest release, we've made changes to address this concern. Dotenv is no longer loaded on initialization by default, which should prevent conflicts with tools like AWS Secret Manager or other Ruby on Rails ENV loading solutions.

You can now control when Dotenv is loaded, giving you more flexibility in how you manage environment variables.

**Closed by dinomh** 2024-12-11 13:48 UTC
